### PR TITLE
Jshint update

### PR DESCRIPTION
**Pull request by lazarDevelopment**
add 'gulp format' - format javascript files with clang-format
'gulp jshint' runs format and jshint
old single jshint is now under 'gulp hint' available.

all js files formated and jshint alerts reduced

### CODE REVIEW

**Comment by malachewhiz** [comment]
On this branch `gulp jshint` produces the following output:
```
[14:33:03] Using gulpfile ~/dev/hoou-webapp/gulpfile.js
[14:33:03] Starting 'format'...
[14:33:03] Starting 'hint'...
client/assets/js/controller/LoginController.js: line 64, col 24, Expected '===' and instead saw '=='.
client/assets/js/controller/LoginController.js: line 86, col 28, Expected '===' and instead saw '=='.

2 errors
client/assets/js/services/LoginOauthService.js: line 71, col 42, 'error' is defined but never used.
client/assets/js/services/LoginOauthService.js: line 97, col 44, ['name'] is better written in dot notation.
client/assets/js/services/LoginOauthService.js: line 81, col 45, 'reject' is defined but never used.
client/assets/js/services/LoginOauthService.js: line 19, col 17, 'current_user' is defined but never used.
client/assets/js/services/LoginOauthService.js: line 19, col 31, 'current_token' is defined but never used.

5 errors
[14:33:04] Finished 'hint' after 824 ms
[14:33:04] Finished 'format' after 836 ms
[14:33:04] Starting 'jshint'...
[14:33:04] Finished 'jshint' after 23 μs
```

Can you tell gulp format to use 2 spaces for indentation (not 4)?

**Comment by lazarDevelopment** [comment]
@malachewhiz it uses already 2 spaces and not 4, e.g:
(function() {
  'use strict';
  angular.module('application')

output is correct. "gulp jshint" runs gulp format and gulp hint
for only check jshint, run "gulp hint"

**Comment by lazarDevelopment** [comment]
@malachewhiz hab task so angepasst, dass hint erst startet wenn format fertig ist.

**Comment by lazarDevelopment** [comment]
@malachewhiz please review again.

**Comment by malachewhiz** [comment]
If it would start the tasks in order, the output would be
    Starting format
    Finished format
    Starting hint
    Finished hint
but the current implementation starts both tasks parallel (so its indeterministic which task finishes first).

One could make the format task a [prerequisite](http://stackoverflow.com/a/26390567) of the jshint task like so:

```js
gulp.task('jshint', ['format'], function () {
  return gulp.start('hint');
});
```

Nevertheless gulp jshint (or gulp hint) produces the same 7 errors.

**Comment by lazarDevelopment** [comment]
@malachewhiz it does not start parallel this makes sure of that:
gulp.task('jshint', function () {
  sequence('format', 'hint');
 });
output is:
[16:25:46] Starting 'jshint'...
[16:25:46] Starting 'format'...
[16:25:46] Finished 'jshint' after 15 ms
[16:25:46] Finished 'format' after 329 ms
[16:25:46] Starting 'hint'...
..

**Comment by lazarDevelopment** [comment]
@malachewhiz all hints removed: please review again

**Comment by malachewhiz** [comment]
Ok
Merge please.

**Pull request merged**
