### PR TITLE
Bookmark oranges

### PR DESCRIPTION
**Pull request by lazarDevelopment**

### CODE REVIEW

**Comment by malachewhiz** [comment]
With a logged-in user everything works fine, but without login no public bookmarks are shown.

The following JS error is logged:

```js
TypeError: Cannot read property 'access_token' of null
at Object.getBookmarksFromUser
at Scope.BookmarkController.$scope.getBookmarksFromUser
```

**Comment by lazarDevelopment** [comment]
@malachewhiz your comment is fixed. please review again

**Comment by malachewhiz** [comment]
2 Issues:

+  The details of private bookmarks are rendered on click, but public bookmarks' details aren't (regardless of login status).
+ Without a login, the create bookmark button is rendered. It renders the form on click, so the user is able to fill in the bookmark details and only after clicking submit the 401 error is thrown. Without a login you shouldn't be able to see the button and the form.

**Comment by lazarDevelopment** [comment]
@malachewhiz both issues are fixed. please review again

**Comment by malachewhiz** [comment]
Second issue is fixed, but the first one hasn't changed. No bookmark under 'All Bookmarks' is accessible.

**Comment by malachewhiz** [comment]
Ok!
:+1:
Merge please (and delete the branches).

**Pull request merged**
